"""initial schema

Revision ID: d91c476d9e9a
Revises: 
Create Date: 2026-03-24 09:44:14.763822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91c476d9e9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('mechanics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('service_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('VIN', sa.String(length=17), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('VIN', 'service_date', name='uq_vin_service_date')
    )
    op.create_table('inventory_service_ticket',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('service_ticket_id', sa.Integer(), nullable=False),
    sa.Column('quantity_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['service_ticket_id'], ['service_tickets.id'], ),
    sa.PrimaryKeyConstraint('inventory_id', 'service_ticket_id')
    )
    op.create_table('mechanic_tickets',
    sa.Column('mechanic_id', sa.Integer(), nullable=False),
    sa.Column('service_ticket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanics.id'], ),
    sa.ForeignKeyConstraint(['service_ticket_id'], ['service_tickets.id'], ),
    sa.PrimaryKeyConstraint('mechanic_id', 'service_ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mechanic_tickets')
    op.drop_table('inventory_service_ticket')
    op.drop_table('service_tickets')
    op.drop_table('mechanics')
    op.drop_table('customers')
    op.drop_table('roles')
    op.drop_table('inventory')
    # ### end Alembic commands ###
